version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
      day: monday
    groups:
      minor-and-patch:
        update-types: ["minor", "patch"]
    open-pull-requests-limit: 10
    labels: [dependencies]
    commit-message:
      prefix: build

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    labels: [dependencies, ci]
    commit-message:
      prefix: ci

  - package-ecosystem: docker
    directory: "/docker"
    schedule:
      interval: weekly
    labels: [dependencies, docker]
    commit-message:
      prefix: build

  - package-ecosystem: terraform
    directory: "/infrastructure/terraform/aws"
    schedule:
      interval: monthly
    labels: [dependencies, infrastructure]
