apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: sylvara
resources:
  - namespace.yaml
  - configmap.yaml
  - website-deployment.yaml
  - website-service.yaml
  - website-hpa.yaml
  - bots-deployment.yaml
  - services-deployment.yaml
  - ingress.yaml
  - postgres-pvc.yaml
